# Generated by Django 4.0.4 on 2023-07-05 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teacherId', models.CharField(max_length=255)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('weekDays', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=255, null=True)),
                ('firstName', models.CharField(max_length=255, null=True)),
                ('startDate', models.DateTimeField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('parentPhone1', models.CharField(max_length=255, null=True)),
                ('parentPhone2', models.CharField(max_length=255, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('userId', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField()),
                ('groupId', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('lastUpdated', models.DateTimeField()),
                ('lastUpdatedBy', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerias_production.group')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerias_production.person')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(null=True)),
                ('contactId', models.IntegerField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('userType', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255, null=True)),
                ('admin', models.BooleanField(null=True)),
                ('person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerias_production.person')),
            ],
        ),
    ]
