# Generated by Django 4.0.4 on 2023-07-05 05:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='created_by',
        ),
        migrations.AddField(
            model_name='appuser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appuser',
            name='createdBy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_appuser', to='jerias_production.person'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='lastUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appuser',
            name='lastUpdatedBy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_appuser', to='jerias_production.person'),
        ),
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='group',
            name='createdBy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_group', to='jerias_production.person'),
        ),
        migrations.AddField(
            model_name='group',
            name='lastUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='group',
            name='lastUpdatedBy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_group', to='jerias_production.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='createdBy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='lastUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='lastUpdatedBy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jerias_production.person'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='groupperson',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupperson',
            name='createdBy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_groupperson', to='jerias_production.person'),
        ),
        migrations.AlterField(
            model_name='groupperson',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_people', to='jerias_production.group'),
        ),
        migrations.AlterField(
            model_name='groupperson',
            name='lastUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupperson',
            name='lastUpdatedBy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_groupperson', to='jerias_production.person'),
        ),
        migrations.AlterField(
            model_name='groupperson',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='groupperson',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_participations', to='jerias_production.person'),
        ),
    ]
