# Generated by Django 4.0.4 on 2023-07-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0002_remove_appuser_created_by_appuser_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created',
        ),
        migrations.RemoveField(
            model_name='person',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lastUpdated',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lastUpdatedBy',
        ),
    ]
