# Generated by Django 4.0.4 on 2023-07-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0005_alter_groupperson_createdby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('lastUpdated', models.DateTimeField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='jerias_production.person')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jerias_production.group')),
                ('lastUpdatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_events', to='jerias_production.person')),
            ],
        ),
    ]
