# Generated by Django 4.0.4 on 2023-07-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0007_group_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('createdBy', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('lastUpdated', models.DateTimeField()),
                ('lastUpdatedBy', models.IntegerField()),
                ('status', models.IntegerField()),
                ('groupEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jerias_production.groupevent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jerias_production.person')),
            ],
        ),
    ]
