# Generated by Django 4.0.4 on 2023-07-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0008_studentattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_events', to='jerias_production.person'),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jerias_production.group'),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='lastUpdatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_events', to='jerias_production.person'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
