# Generated by Django 4.0.4 on 2023-07-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0009_alter_groupevent_createdby_alter_groupevent_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacherId',
        ),
    ]
