# Generated by Django 4.0.4 on 2023-07-11 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0010_remove_group_teacherid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('startDate', models.DateTimeField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('endDate', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='jerias_production.account')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_owner_data', to='jerias_production.person')),
            ],
        ),
    ]
