# Generated by Django 4.0.4 on 2023-07-11 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0011_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('lastUpdated', models.DateTimeField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('maxAttendances', models.IntegerField(null=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_created', to='jerias_production.person')),
                ('lastUpdatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_updated', to='jerias_production.person')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='jerias_production.person')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment', serialize=False, to='jerias_production.purchase')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('paymentType', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('cheque', 'Cheque'), ('bit', 'Bit')], max_length=20)),
                ('chequeNumber', models.CharField(blank=True, max_length=50)),
                ('chequeBank', models.CharField(blank=True, max_length=100)),
                ('chequeDate', models.DateTimeField(null=True)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jerias_production.account')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_created', to='jerias_production.person')),
                ('lastUpdatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_updated', to='jerias_production.person')),
            ],
        ),
    ]
