# Generated by Django 4.0.4 on 2023-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0013_purchase_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('value', models.CharField(max_length=20, null=True)),
                ('seq', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('desc', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
