# Generated by Django 4.0.4 on 2023-07-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0014_lookuptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookuptable',
            name='lang',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lookuptable',
            unique_together={('type', 'code', 'lang')},
        ),
    ]
