# Generated by Django 4.0.4 on 2023-07-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0015_lookuptable_lang_alter_lookuptable_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='autoGenerate',
            field=models.BooleanField(default=False),
        ),
    ]
