# Generated by Django 4.0.4 on 2023-07-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0016_purchase_autogenerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentType',
            field=models.IntegerField(null=True),
        ),
    ]
