# Generated by Django 4.0.4 on 2023-07-17 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jerias_production', '0021_alter_appuser_createdby_alter_appuser_lastupdatedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jerias_production.purchase')),
                ('studentAttendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jerias_production.studentattendance')),
            ],
        ),
    ]
